"""add usuarios e materias.usuario_id

Revision ID: 1b48d9db9dbd
Revises: 
Create Date: 2026-07-08 18:01:46.222600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b48d9db9dbd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('ia_chamadas_data', sa.Date(), nullable=True),
    sa.Column('ia_chamadas_contagem', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_id'), ['id'], unique=False)

    with op.batch_alter_table('materias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_materias_nome'))
        batch_op.create_index(batch_op.f('ix_materias_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_materias_usuario_id'), ['usuario_id'], unique=False)
        batch_op.create_unique_constraint('uq_materia_por_usuario', ['usuario_id', 'nome'])
        batch_op.create_foreign_key(
            'fk_materias_usuario_id_usuarios', 'usuarios', ['usuario_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materias', schema=None) as batch_op:
        batch_op.drop_constraint('fk_materias_usuario_id_usuarios', type_='foreignkey')
        batch_op.drop_constraint('uq_materia_por_usuario', type_='unique')
        batch_op.drop_index(batch_op.f('ix_materias_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_materias_nome'))
        batch_op.create_index(batch_op.f('ix_materias_nome'), ['nome'], unique=1)
        batch_op.drop_column('usuario_id')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    # ### end Alembic commands ###
