"""materias usuario_id fk on delete cascade

Revision ID: 6e1803397d26
Revises: f76eeff9c32d
Create Date: 2026-07-08 18:31:42.669504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e1803397d26'
down_revision: Union[str, Sequence[str], None] = 'f76eeff9c32d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materias', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_materias_usuario_id_usuarios'), type_='foreignkey')
        batch_op.create_foreign_key(
            'fk_materias_usuario_id_usuarios',
            'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE',
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materias', schema=None) as batch_op:
        batch_op.drop_constraint('fk_materias_usuario_id_usuarios', type_='foreignkey')
        batch_op.create_foreign_key(
            'fk_materias_usuario_id_usuarios', 'usuarios', ['usuario_id'], ['id']
        )

    # ### end Alembic commands ###
