-- Study Rats — schema inicial (Supabase/Postgres)
--
-- Segurança (deny-by-default):
--   * anon: nenhum acesso a nada — o app exige login para tudo.
--   * authenticated: acesso apenas via políticas de RLS por operação.
--   * Toda função SECURITY DEFINER usa SET search_path = ''.
--   * perfis (quota de IA): usuário só lê a própria linha; escrita apenas
--     pela função consumir_quota_ia (definer) e pelo trigger de signup.

-- =========================================================
-- Tabelas
-- =========================================================

create table public.perfis (
  user_id uuid primary key references auth.users (id) on delete cascade,
  ia_chamadas_data date,
  ia_chamadas_contagem integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.materias (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  nome varchar(150) not null,
  descricao text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_materia_por_usuario unique (usuario_id, nome)
);
create index ix_materias_usuario_id on public.materias (usuario_id);

create table public.subdivisoes (
  id bigint generated by default as identity primary key,
  materia_id bigint not null references public.materias (id) on delete cascade,
  nome varchar(150) not null,
  descricao text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_subdivisao_por_materia unique (materia_id, nome)
);
create index ix_subdivisoes_materia_id on public.subdivisoes (materia_id);

create table public.perguntas (
  id bigint generated by default as identity primary key,
  subdivisao_id bigint not null references public.subdivisoes (id) on delete cascade,
  enunciado text not null,
  dificuldade varchar(50) not null,
  origem varchar(50),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index ix_perguntas_subdivisao_id on public.perguntas (subdivisao_id);

create table public.opcoes (
  id bigint generated by default as identity primary key,
  pergunta_id bigint not null references public.perguntas (id) on delete cascade,
  texto text not null,
  correta boolean not null default false,
  ordem integer not null,
  created_at timestamptz not null default now()
);
create index ix_opcoes_pergunta_id on public.opcoes (pergunta_id);

create table public.revisoes_perguntas (
  id bigint generated by default as identity primary key,
  pergunta_id bigint not null unique references public.perguntas (id) on delete cascade,
  vezes_respondida integer not null default 0,
  vezes_acertada integer not null default 0,
  vezes_errada integer not null default 0,
  ultima_resposta_correta boolean,
  ultima_respondida_em timestamptz,
  proxima_revisao_em timestamptz,
  intervalo_dias integer not null default 0,
  fator_facilidade integer not null default 250,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =========================================================
-- Trigger: cria o perfil (quota de IA) em todo signup
-- =========================================================

create function public.criar_perfil()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.perfis (user_id) values (new.id)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.criar_perfil();

-- =========================================================
-- Privilégios: anon não acessa NADA no schema public
-- =========================================================

revoke all on all tables in schema public from anon;
revoke all on all sequences in schema public from anon;
revoke all on all functions in schema public from anon;
alter default privileges in schema public revoke all on tables from anon;
alter default privileges in schema public revoke all on sequences from anon;
alter default privileges in schema public revoke all on functions from anon;

-- =========================================================
-- RLS deny-by-default, políticas por operação
-- =========================================================

alter table public.perfis enable row level security;
alter table public.materias enable row level security;
alter table public.subdivisoes enable row level security;
alter table public.perguntas enable row level security;
alter table public.opcoes enable row level security;
alter table public.revisoes_perguntas enable row level security;

-- perfis: apenas leitura da própria linha (escrita só via definer/trigger)
create policy perfis_select on public.perfis
  for select to authenticated
  using (user_id = (select auth.uid()));

-- materias
create policy materias_select on public.materias
  for select to authenticated
  using (usuario_id = (select auth.uid()));
create policy materias_insert on public.materias
  for insert to authenticated
  with check (usuario_id = (select auth.uid()));
create policy materias_update on public.materias
  for update to authenticated
  using (usuario_id = (select auth.uid()))
  with check (usuario_id = (select auth.uid()));
create policy materias_delete on public.materias
  for delete to authenticated
  using (usuario_id = (select auth.uid()));

-- subdivisoes: dono via materia
create policy subdivisoes_select on public.subdivisoes
  for select to authenticated
  using (exists (
    select 1 from public.materias m
    where m.id = materia_id and m.usuario_id = (select auth.uid())
  ));
create policy subdivisoes_insert on public.subdivisoes
  for insert to authenticated
  with check (exists (
    select 1 from public.materias m
    where m.id = materia_id and m.usuario_id = (select auth.uid())
  ));
create policy subdivisoes_update on public.subdivisoes
  for update to authenticated
  using (exists (
    select 1 from public.materias m
    where m.id = materia_id and m.usuario_id = (select auth.uid())
  ))
  with check (exists (
    select 1 from public.materias m
    where m.id = materia_id and m.usuario_id = (select auth.uid())
  ));
create policy subdivisoes_delete on public.subdivisoes
  for delete to authenticated
  using (exists (
    select 1 from public.materias m
    where m.id = materia_id and m.usuario_id = (select auth.uid())
  ));

-- perguntas: dono via subdivisao -> materia
create policy perguntas_select on public.perguntas
  for select to authenticated
  using (exists (
    select 1 from public.subdivisoes s
    join public.materias m on m.id = s.materia_id
    where s.id = subdivisao_id and m.usuario_id = (select auth.uid())
  ));
create policy perguntas_insert on public.perguntas
  for insert to authenticated
  with check (exists (
    select 1 from public.subdivisoes s
    join public.materias m on m.id = s.materia_id
    where s.id = subdivisao_id and m.usuario_id = (select auth.uid())
  ));
create policy perguntas_update on public.perguntas
  for update to authenticated
  using (exists (
    select 1 from public.subdivisoes s
    join public.materias m on m.id = s.materia_id
    where s.id = subdivisao_id and m.usuario_id = (select auth.uid())
  ))
  with check (exists (
    select 1 from public.subdivisoes s
    join public.materias m on m.id = s.materia_id
    where s.id = subdivisao_id and m.usuario_id = (select auth.uid())
  ));
create policy perguntas_delete on public.perguntas
  for delete to authenticated
  using (exists (
    select 1 from public.subdivisoes s
    join public.materias m on m.id = s.materia_id
    where s.id = subdivisao_id and m.usuario_id = (select auth.uid())
  ));

-- opcoes: dono via pergunta -> subdivisao -> materia
create policy opcoes_select on public.opcoes
  for select to authenticated
  using (exists (
    select 1 from public.perguntas p
    join public.subdivisoes s on s.id = p.subdivisao_id
    join public.materias m on m.id = s.materia_id
    where p.id = pergunta_id and m.usuario_id = (select auth.uid())
  ));
create policy opcoes_insert on public.opcoes
  for insert to authenticated
  with check (exists (
    select 1 from public.perguntas p
    join public.subdivisoes s on s.id = p.subdivisao_id
    join public.materias m on m.id = s.materia_id
    where p.id = pergunta_id and m.usuario_id = (select auth.uid())
  ));
create policy opcoes_update on public.opcoes
  for update to authenticated
  using (exists (
    select 1 from public.perguntas p
    join public.subdivisoes s on s.id = p.subdivisao_id
    join public.materias m on m.id = s.materia_id
    where p.id = pergunta_id and m.usuario_id = (select auth.uid())
  ))
  with check (exists (
    select 1 from public.perguntas p
    join public.subdivisoes s on s.id = p.subdivisao_id
    join public.materias m on m.id = s.materia_id
    where p.id = pergunta_id and m.usuario_id = (select auth.uid())
  ));
create policy opcoes_delete on public.opcoes
  for delete to authenticated
  using (exists (
    select 1 from public.perguntas p
    join public.subdivisoes s on s.id = p.subdivisao_id
    join public.materias m on m.id = s.materia_id
    where p.id = pergunta_id and m.usuario_id = (select auth.uid())
  ));

-- revisoes_perguntas: mesma cadeia de dono
create policy revisoes_select on public.revisoes_perguntas
  for select to authenticated
  using (exists (
    select 1 from public.perguntas p
    join public.subdivisoes s on s.id = p.subdivisao_id
    join public.materias m on m.id = s.materia_id
    where p.id = pergunta_id and m.usuario_id = (select auth.uid())
  ));
create policy revisoes_insert on public.revisoes_perguntas
  for insert to authenticated
  with check (exists (
    select 1 from public.perguntas p
    join public.subdivisoes s on s.id = p.subdivisao_id
    join public.materias m on m.id = s.materia_id
    where p.id = pergunta_id and m.usuario_id = (select auth.uid())
  ));
create policy revisoes_update on public.revisoes_perguntas
  for update to authenticated
  using (exists (
    select 1 from public.perguntas p
    join public.subdivisoes s on s.id = p.subdivisao_id
    join public.materias m on m.id = s.materia_id
    where p.id = pergunta_id and m.usuario_id = (select auth.uid())
  ))
  with check (exists (
    select 1 from public.perguntas p
    join public.subdivisoes s on s.id = p.subdivisao_id
    join public.materias m on m.id = s.materia_id
    where p.id = pergunta_id and m.usuario_id = (select auth.uid())
  ));
create policy revisoes_delete on public.revisoes_perguntas
  for delete to authenticated
  using (exists (
    select 1 from public.perguntas p
    join public.subdivisoes s on s.id = p.subdivisao_id
    join public.materias m on m.id = s.materia_id
    where p.id = pergunta_id and m.usuario_id = (select auth.uid())
  ));

-- =========================================================
-- Funções RPC
-- =========================================================

-- SM-2 (porta fiel de src/srs.py): acerto q=5, erro q=2; EF com piso 1.3;
-- progressão 1 -> 6 -> round(intervalo * EF); erro zera o intervalo e
-- reagenda para +10 minutos. SECURITY INVOKER: o RLS acima garante que só
-- o dono da pergunta encontra/atualiza a linha de revisão.
create function public.registrar_resposta(p_pergunta_id bigint, p_correta boolean)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  r public.revisoes_perguntas%rowtype;
  q integer;
  novo_ef numeric;
  novo_intervalo integer;
  proxima timestamptz;
begin
  select * into r
  from public.revisoes_perguntas
  where pergunta_id = p_pergunta_id
  for update;

  if not found then
    raise exception 'Pergunta não encontrada.';
  end if;

  q := case when p_correta then 5 else 2 end;
  novo_ef := greatest(
    (r.fator_facilidade / 100.0) + (0.1 - (5 - q) * (0.08 + (5 - q) * 0.02)),
    1.3
  );

  if q < 3 then
    novo_intervalo := 0;
    proxima := now() + interval '10 minutes';
  else
    if r.intervalo_dias <= 0 then
      novo_intervalo := 1;
    elsif r.intervalo_dias = 1 then
      novo_intervalo := 6;
    else
      novo_intervalo := round(r.intervalo_dias * novo_ef)::integer;
    end if;
    proxima := now() + make_interval(days => novo_intervalo);
  end if;

  update public.revisoes_perguntas set
    vezes_respondida = r.vezes_respondida + 1,
    vezes_acertada = r.vezes_acertada + (case when p_correta then 1 else 0 end),
    vezes_errada = r.vezes_errada + (case when p_correta then 0 else 1 end),
    ultima_resposta_correta = p_correta,
    ultima_respondida_em = now(),
    fator_facilidade = round(novo_ef * 100)::integer,
    intervalo_dias = novo_intervalo,
    proxima_revisao_em = proxima,
    updated_at = now()
  where pergunta_id = p_pergunta_id;

  return jsonb_build_object(
    'intervalo_dias', novo_intervalo,
    'proxima_revisao_em', proxima,
    'vezes_respondida', r.vezes_respondida + 1,
    'vezes_acertada', r.vezes_acertada + (case when p_correta then 1 else 0 end),
    'ultima_resposta_correta', p_correta
  );
end;
$$;

-- Resumo por matéria para o dashboard (porta de resumo_materias).
create function public.resumo_materias()
returns table (id bigint, nome varchar, total_perguntas bigint, devidas_revisao bigint)
language sql
security invoker
set search_path = ''
stable
as $$
  select
    m.id,
    m.nome,
    count(p.id) as total_perguntas,
    count(p.id) filter (
      where rp.proxima_revisao_em is null or rp.proxima_revisao_em <= now()
    ) as devidas_revisao
  from public.materias m
  left join public.subdivisoes s on s.materia_id = m.id
  left join public.perguntas p on p.subdivisao_id = s.id
  left join public.revisoes_perguntas rp on rp.pergunta_id = p.id
  where m.usuario_id = (select auth.uid())
  group by m.id, m.nome
  order by m.nome asc;
$$;

-- Quota diária de IA (porta de verificar_e_incrementar_quota_ia).
-- SECURITY DEFINER porque o usuário NÃO tem permissão de escrita em perfis;
-- search_path fixado vazio contra hijack.
create function public.consumir_quota_ia(p_limite integer)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := (select auth.uid());
  v_contagem integer;
  v_data date;
begin
  if v_uid is null then
    return false;
  end if;

  insert into public.perfis (user_id) values (v_uid)
  on conflict (user_id) do nothing;

  select ia_chamadas_contagem, ia_chamadas_data
  into v_contagem, v_data
  from public.perfis
  where user_id = v_uid
  for update;

  if v_data is distinct from current_date then
    v_contagem := 0;
  end if;

  if v_contagem >= p_limite then
    update public.perfis
    set ia_chamadas_data = current_date, ia_chamadas_contagem = v_contagem
    where user_id = v_uid;
    return false;
  end if;

  update public.perfis
  set ia_chamadas_data = current_date, ia_chamadas_contagem = v_contagem + 1
  where user_id = v_uid;

  return true;
end;
$$;

-- Execução das funções: somente usuários logados.
revoke execute on function public.registrar_resposta(bigint, boolean) from public, anon;
revoke execute on function public.resumo_materias() from public, anon;
revoke execute on function public.consumir_quota_ia(integer) from public, anon;
revoke execute on function public.criar_perfil() from public, anon, authenticated;
grant execute on function public.registrar_resposta(bigint, boolean) to authenticated;
grant execute on function public.resumo_materias() to authenticated;
grant execute on function public.consumir_quota_ia(integer) to authenticated;
