-- Catálogo público de provas (ENEM, concursos, vestibulares, certificações).
--
-- Curadoria acontece FORA do app (ferramentas/provas): scraping de fontes
-- oficiais + revisão manual + publicação com credencial administrativa.
-- Usuários apenas LEEM o catálogo e importam provas para a própria conta
-- via importar_prova_catalogo() — que roda como SECURITY INVOKER, então
-- toda a escrita passa pelo RLS normal da conta de quem importa.

create table public.catalogo_provas (
  id bigint generated by default as identity primary key,
  fonte varchar(40) not null,          -- 'enem', 'cebraspe', 'fuvest', ...
  nome varchar(200) not null,          -- ex.: 'ENEM 2023 — Ciências Humanas'
  ano integer,
  area varchar(120),
  total_questoes integer not null default 0,
  publicada_em timestamptz not null default now(),
  constraint uq_catalogo_prova unique (fonte, nome)
);

create table public.catalogo_questoes (
  id bigint generated by default as identity primary key,
  prova_id bigint not null references public.catalogo_provas (id) on delete cascade,
  numero integer,
  enunciado text not null,
  topico varchar(150)
);
create index ix_catalogo_questoes_prova on public.catalogo_questoes (prova_id);

create table public.catalogo_alternativas (
  id bigint generated by default as identity primary key,
  questao_id bigint not null references public.catalogo_questoes (id) on delete cascade,
  texto text not null,
  correta boolean not null default false,
  ordem integer not null
);
create index ix_catalogo_alternativas_questao on public.catalogo_alternativas (questao_id);

alter table public.catalogo_provas enable row level security;
alter table public.catalogo_questoes enable row level security;
alter table public.catalogo_alternativas enable row level security;

-- Leitura para qualquer usuário logado; NENHUMA política de escrita.
create policy catalogo_provas_select on public.catalogo_provas
  for select to authenticated using (true);
create policy catalogo_questoes_select on public.catalogo_questoes
  for select to authenticated using (true);
create policy catalogo_alternativas_select on public.catalogo_alternativas
  for select to authenticated using (true);

-- Importa uma prova do catálogo para a conta do usuário logado.
create function public.importar_prova_catalogo(p_prova_id bigint)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_prova public.catalogo_provas%rowtype;
  v_materia_id bigint;
  v_sub_id bigint;
  v_q record;
  v_pergunta_id bigint;
  v_importadas integer := 0;
  v_puladas integer := 0;
begin
  select * into v_prova from public.catalogo_provas where id = p_prova_id;
  if not found then
    raise exception 'Prova % não encontrada no catálogo', p_prova_id;
  end if;

  insert into public.materias (usuario_id, nome)
  values (auth.uid(), v_prova.nome)
  on conflict (usuario_id, nome) do update set updated_at = now()
  returning id into v_materia_id;

  for v_q in
    select q.* from public.catalogo_questoes q
    where q.prova_id = p_prova_id
    order by q.numero nulls last, q.id
  loop
    insert into public.subdivisoes (materia_id, nome)
    values (v_materia_id, coalesce(v_q.topico, 'Geral'))
    on conflict (materia_id, nome) do update set updated_at = now()
    returning id into v_sub_id;

    -- idempotente: reimportar não duplica enunciados já presentes
    if exists (
      select 1
      from public.perguntas p
      join public.subdivisoes s on s.id = p.subdivisao_id
      where s.materia_id = v_materia_id and p.enunciado = v_q.enunciado
    ) then
      v_puladas := v_puladas + 1;
      continue;
    end if;

    insert into public.perguntas (subdivisao_id, enunciado, dificuldade, origem, tipo)
    values (v_sub_id, v_q.enunciado, 'Média', 'catalogo', 'pergunta')
    returning id into v_pergunta_id;

    insert into public.opcoes (pergunta_id, texto, correta, ordem)
    select v_pergunta_id, a.texto, a.correta, a.ordem
    from public.catalogo_alternativas a
    where a.questao_id = v_q.id;

    insert into public.revisoes_perguntas (pergunta_id) values (v_pergunta_id);

    v_importadas := v_importadas + 1;
  end loop;

  return jsonb_build_object(
    'materia_id', v_materia_id,
    'materia_nome', v_prova.nome,
    'importadas', v_importadas,
    'puladas', v_puladas
  );
end;
$$;

revoke execute on function public.importar_prova_catalogo(bigint) from anon;
