-- Variantes de pergunta: versões reformuladas pela IA do MESMO conceito.
--
-- Objetivo: depois de acertar a pergunta várias vezes seguidas, o cérebro
-- passa a reconhecer o formato ("é a terceira") em vez de recuperar o
-- conteúdo. As variantes trocam a roupa da pergunta (enunciado e
-- alternativas reescritos) mantendo o conceito testado.
--
-- Decisões de modelagem:
-- - O SM-2 continua na pergunta-pai (`revisoes_perguntas` é 1:1 com
--   `perguntas`). A variante é só uma APRESENTAÇÃO alternativa: não entra na
--   fila como item novo, não duplica o histórico e não divide o intervalo.
-- - `opcoes` fica em jsonb (e não numa tabela filha como `opcoes`): variante
--   é conteúdo derivado e descartável; evita uma 4ª camada de RLS.
-- - O original NUNCA é apagado — ele continua na rotação junto das variantes
--   (importante para questões de prova real, cuja redação da banca importa).
-- - A rotação NÃO é guardada aqui: o front escolhe por
--   `vezes_respondida % (1 + nº de variantes ativas)`. É determinístico
--   (estável no reload/"Voltar") e evita um UPDATE a cada exibição.

create table public.pergunta_variantes (
  id bigint generated by default as identity primary key,
  pergunta_id bigint not null references public.perguntas (id) on delete cascade,
  enunciado text not null,
  opcoes jsonb not null,
  descartada boolean not null default false,
  created_at timestamptz not null default now(),
  constraint pergunta_variantes_opcoes_check check (
    jsonb_typeof(opcoes) = 'array'
    and jsonb_array_length(opcoes) between 2 and 8
    -- pelo menos uma alternativa correta (jsonpath: sem subquery, válido em CHECK)
    and opcoes @? '$[*] ? (@.correta == true)'
  )
);
create index ix_pergunta_variantes_pergunta_id on public.pergunta_variantes (pergunta_id);

alter table public.pergunta_variantes enable row level security;

-- Mesma cadeia de dono das demais tabelas: variante -> pergunta -> subdivisão
-- -> matéria. WITH CHECK no insert/update bloqueia IDOR de escrita.
create policy variantes_select on public.pergunta_variantes
  for select to authenticated
  using (exists (
    select 1 from public.perguntas p
    join public.subdivisoes s on s.id = p.subdivisao_id
    join public.materias m on m.id = s.materia_id
    where p.id = pergunta_id and m.usuario_id = (select auth.uid())
  ));
create policy variantes_insert on public.pergunta_variantes
  for insert to authenticated
  with check (exists (
    select 1 from public.perguntas p
    join public.subdivisoes s on s.id = p.subdivisao_id
    join public.materias m on m.id = s.materia_id
    where p.id = pergunta_id and m.usuario_id = (select auth.uid())
  ));
create policy variantes_update on public.pergunta_variantes
  for update to authenticated
  using (exists (
    select 1 from public.perguntas p
    join public.subdivisoes s on s.id = p.subdivisao_id
    join public.materias m on m.id = s.materia_id
    where p.id = pergunta_id and m.usuario_id = (select auth.uid())
  ))
  with check (exists (
    select 1 from public.perguntas p
    join public.subdivisoes s on s.id = p.subdivisao_id
    join public.materias m on m.id = s.materia_id
    where p.id = pergunta_id and m.usuario_id = (select auth.uid())
  ));
create policy variantes_delete on public.pergunta_variantes
  for delete to authenticated
  using (exists (
    select 1 from public.perguntas p
    join public.subdivisoes s on s.id = p.subdivisao_id
    join public.materias m on m.id = s.materia_id
    where p.id = pergunta_id and m.usuario_id = (select auth.uid())
  ));

-- Hardening: o revoke de 0012 valeu só para as tabelas que existiam então.
-- Tabela nova recebe os grants padrão do Supabase — repetir aqui mantém a
-- postura (anon sem nada; authenticated sem privilégios que o RLS não filtra).
revoke all on public.pergunta_variantes from anon;
revoke truncate, trigger, references on public.pergunta_variantes from authenticated;

-- Acertos consecutivos: o gatilho das variantes é "acertei N vezes seguidas".
-- `vezes_acertada` não serve (é acumulado e não zera no erro).
alter table public.revisoes_perguntas
  add column acertos_seguidos integer not null default 0;

-- registrar_resposta: mesma SM-2 de sempre (validada 1:1 contra src/srs.py),
-- acrescida APENAS da manutenção de acertos_seguidos.
create or replace function public.registrar_resposta(p_pergunta_id bigint, p_correta boolean)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  r public.revisoes_perguntas%rowtype;
  q integer;
  novo_ef numeric;
  novo_intervalo integer;
  proxima timestamptz;
  novos_seguidos integer;
begin
  select * into r
  from public.revisoes_perguntas
  where pergunta_id = p_pergunta_id
  for update;

  if not found then
    raise exception 'Pergunta não encontrada.';
  end if;

  q := case when p_correta then 5 else 2 end;
  novo_ef := greatest(
    (r.fator_facilidade / 100.0) + (0.1 - (5 - q) * (0.08 + (5 - q) * 0.02)),
    1.3
  );

  if q < 3 then
    novo_intervalo := 0;
    proxima := now() + interval '10 minutes';
  else
    if r.intervalo_dias <= 0 then
      novo_intervalo := 1;
    elsif r.intervalo_dias = 1 then
      novo_intervalo := 6;
    else
      novo_intervalo := round(r.intervalo_dias * novo_ef)::integer;
    end if;
    proxima := now() + make_interval(days => novo_intervalo);
  end if;

  novos_seguidos := case when p_correta then r.acertos_seguidos + 1 else 0 end;

  update public.revisoes_perguntas set
    vezes_respondida = r.vezes_respondida + 1,
    vezes_acertada = r.vezes_acertada + (case when p_correta then 1 else 0 end),
    vezes_errada = r.vezes_errada + (case when p_correta then 0 else 1 end),
    ultima_resposta_correta = p_correta,
    ultima_respondida_em = now(),
    fator_facilidade = round(novo_ef * 100)::integer,
    intervalo_dias = novo_intervalo,
    proxima_revisao_em = proxima,
    acertos_seguidos = novos_seguidos,
    updated_at = now()
  where pergunta_id = p_pergunta_id;

  return jsonb_build_object(
    'intervalo_dias', novo_intervalo,
    'proxima_revisao_em', proxima,
    'vezes_respondida', r.vezes_respondida + 1,
    'vezes_acertada', r.vezes_acertada + (case when p_correta then 1 else 0 end),
    'acertos_seguidos', novos_seguidos,
    'ultima_resposta_correta', p_correta
  );
end;
$$;

revoke execute on function public.registrar_resposta(bigint, boolean) from public, anon;
grant execute on function public.registrar_resposta(bigint, boolean) to authenticated;
