-- Lista de exercícios: a 3ª categoria de estudo (ao lado de simulado e
-- flashcard), decidida com o dono. Uma LISTA é uma coleção ordenada de
-- EXERCÍCIOS (de um livro/lista com gabarito), dentro de uma matéria. Estuda-se
-- resolvendo e conferindo; os errados entram na repetição espaçada.
--
-- Reaproveita a infra existente: o exercício É uma `pergunta` (tipo
-- 'exercicio'), então herda revisoes_perguntas (SM-2 em dias úteis), a cadeia
-- de RLS e o cascade. A tabela `exercicios` (1:1) guarda só o que é específico
-- de exercício: a resposta esperada (gabarito), a `verificacao` (o que o código
-- calcula — ver web/js/conferir.js) e a ordem na lista. A resolução passo a
-- passo fica no `verso` da pergunta.

-- ---------- LISTAS ----------
create table public.listas (
  id bigint generated by default as identity primary key,
  materia_id bigint not null references public.materias (id) on delete cascade,
  nome varchar(200) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index ix_listas_materia_id on public.listas (materia_id);

alter table public.listas enable row level security;

-- RLS: dono via matéria (mesmo padrão das demais tabelas).
create policy listas_select on public.listas
  for select to authenticated
  using (exists (select 1 from public.materias m
                 where m.id = materia_id and m.usuario_id = (select auth.uid())));
create policy listas_insert on public.listas
  for insert to authenticated
  with check (exists (select 1 from public.materias m
                      where m.id = materia_id and m.usuario_id = (select auth.uid())));
create policy listas_update on public.listas
  for update to authenticated
  using (exists (select 1 from public.materias m
                 where m.id = materia_id and m.usuario_id = (select auth.uid())))
  with check (exists (select 1 from public.materias m
                      where m.id = materia_id and m.usuario_id = (select auth.uid())));
create policy listas_delete on public.listas
  for delete to authenticated
  using (exists (select 1 from public.materias m
                 where m.id = materia_id and m.usuario_id = (select auth.uid())));

-- Hardening (o revoke de 0012 só valeu p/ tabelas que existiam então).
revoke all on public.listas from anon;
revoke truncate, trigger, references on public.listas from authenticated;

-- ---------- PERGUNTAS: novo tipo 'exercicio' + vínculo com a lista ----------
alter table public.perguntas
  drop constraint perguntas_tipo_check,
  add constraint perguntas_tipo_check check (tipo in ('pergunta', 'flashcard', 'exercicio')),
  -- exercício pertence a uma lista; apagar a lista apaga seus exercícios.
  add column lista_id bigint references public.listas (id) on delete cascade;
create index ix_perguntas_lista_id on public.perguntas (lista_id);

-- ---------- EXERCICIOS: dados específicos do exercício (1:1 com a pergunta) ----------
create table public.exercicios (
  id bigint generated by default as identity primary key,
  pergunta_id bigint not null unique references public.perguntas (id) on delete cascade,
  resposta_esperada text,                -- gabarito (curto): "F", "V(p)=F", "x=-3"
  verificacao jsonb,                     -- o que o código calcula (conferir.js)
  ordem integer not null default 0,      -- posição na lista
  constraint exercicios_verificacao_check
    check (verificacao is null or jsonb_typeof(verificacao) = 'object')
);
create index ix_exercicios_pergunta_id on public.exercicios (pergunta_id);

alter table public.exercicios enable row level security;

-- RLS: dono via pergunta → subdivisão → matéria (igual a opcoes/revisoes).
create policy exercicios_select on public.exercicios
  for select to authenticated
  using (exists (
    select 1 from public.perguntas p
    join public.subdivisoes s on s.id = p.subdivisao_id
    join public.materias m on m.id = s.materia_id
    where p.id = pergunta_id and m.usuario_id = (select auth.uid())
  ));
create policy exercicios_insert on public.exercicios
  for insert to authenticated
  with check (exists (
    select 1 from public.perguntas p
    join public.subdivisoes s on s.id = p.subdivisao_id
    join public.materias m on m.id = s.materia_id
    where p.id = pergunta_id and m.usuario_id = (select auth.uid())
  ));
create policy exercicios_update on public.exercicios
  for update to authenticated
  using (exists (
    select 1 from public.perguntas p
    join public.subdivisoes s on s.id = p.subdivisao_id
    join public.materias m on m.id = s.materia_id
    where p.id = pergunta_id and m.usuario_id = (select auth.uid())
  ))
  with check (exists (
    select 1 from public.perguntas p
    join public.subdivisoes s on s.id = p.subdivisao_id
    join public.materias m on m.id = s.materia_id
    where p.id = pergunta_id and m.usuario_id = (select auth.uid())
  ));
create policy exercicios_delete on public.exercicios
  for delete to authenticated
  using (exists (
    select 1 from public.perguntas p
    join public.subdivisoes s on s.id = p.subdivisao_id
    join public.materias m on m.id = s.materia_id
    where p.id = pergunta_id and m.usuario_id = (select auth.uid())
  ));

revoke all on public.exercicios from anon;
revoke truncate, trigger, references on public.exercicios from authenticated;
