-- TRILHAS: uma camada acima de `materias` para agrupar o que pertence ao mesmo
-- contexto de estudo — "Estatística UFPR", "Certificações AWS", "Concursos".
-- É só organização: o estudo continua escopado por matéria.
--
-- Decisão importante: `materias.trilha_id` é ON DELETE SET NULL (e não CASCADE).
-- Apagar uma trilha NÃO pode levar junto as matérias e todo o conteúdo de
-- estudo — ela é uma etiqueta de organização, não a dona dos dados. Matéria sem
-- trilha é válida (fica no grupo "Sem trilha").

create table public.trilhas (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  nome varchar(150) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_trilha_por_usuario unique (usuario_id, nome)
);
create index ix_trilhas_usuario_id on public.trilhas (usuario_id);

alter table public.materias
  add column trilha_id bigint references public.trilhas (id) on delete set null;
create index ix_materias_trilha_id on public.materias (trilha_id);

-- RLS: mesmo padrão de `materias` — o usuário só enxerga/escreve as próprias
-- linhas. WITH CHECK no insert/update impede gravar linha em nome de outro.
alter table public.trilhas enable row level security;

create policy trilhas_select on public.trilhas
  for select to authenticated
  using (usuario_id = (select auth.uid()));
create policy trilhas_insert on public.trilhas
  for insert to authenticated
  with check (usuario_id = (select auth.uid()));
create policy trilhas_update on public.trilhas
  for update to authenticated
  using (usuario_id = (select auth.uid()))
  with check (usuario_id = (select auth.uid()));
create policy trilhas_delete on public.trilhas
  for delete to authenticated
  using (usuario_id = (select auth.uid()));

-- Hardening da 0012 repetido para a tabela NOVA: o `revoke ... on all tables`
-- de lá só valeu para as que existiam na época. `anon` não recebe nada.
revoke all on public.trilhas from anon, public;
grant select, insert, update, delete on public.trilhas to authenticated;
revoke truncate, trigger, references on public.trilhas from authenticated;

-- ---------------------------------------------------------------------------
-- resumo_materias: passa a devolver a trilha (para o app agrupar sem uma query
-- extra) e a separar `a_aprender` de `a_revisar`.
--
-- Correção junto: o front já lia `a_aprender`/`a_revisar` (dashboard e badge do
-- seletor de matéria), mas a função só devolvia `devidas_revisao` — então esses
-- contadores apareciam sempre ZERADOS. `devidas_revisao` continua existindo
-- para não quebrar nada que ainda dependa dele.
--
-- Itens OCULTOS (0024) não entram em contagem alguma de pendência, para o número
-- bater com a fila do Aprendizado, que também os ignora.
-- Muda o tipo de retorno, então exige DROP antes do CREATE.
-- ---------------------------------------------------------------------------
drop function if exists public.resumo_materias();

create function public.resumo_materias()
returns table (
  id bigint,
  nome varchar,
  tipo varchar,
  trilha_id bigint,
  trilha_nome varchar,
  total_perguntas bigint,
  total_flashcards bigint,
  devidas_revisao bigint,
  a_aprender bigint,
  a_revisar bigint
)
language sql
security invoker
set search_path = ''
stable
as $$
  select
    m.id,
    m.nome,
    m.tipo,
    m.trilha_id,
    t.nome as trilha_nome,
    count(p.id) filter (where p.tipo = 'pergunta') as total_perguntas,
    count(p.id) filter (where p.tipo = 'flashcard') as total_flashcards,
    count(p.id) filter (
      where p.tipo in ('pergunta', 'flashcard') and not p.oculta
        and (rp.proxima_revisao_em is null or rp.proxima_revisao_em <= now())
    ) as devidas_revisao,
    -- "a aprender": nunca respondido (novo)
    count(p.id) filter (
      where p.tipo in ('pergunta', 'flashcard') and not p.oculta
        and coalesce(rp.vezes_respondida, 0) = 0
    ) as a_aprender,
    -- "a revisar": já respondido e com a revisão vencida
    count(p.id) filter (
      where p.tipo in ('pergunta', 'flashcard') and not p.oculta
        and coalesce(rp.vezes_respondida, 0) > 0
        and rp.proxima_revisao_em <= now()
    ) as a_revisar
  from public.materias m
  left join public.trilhas t on t.id = m.trilha_id
  left join public.subdivisoes s on s.materia_id = m.id
  left join public.perguntas p on p.subdivisao_id = s.id
  left join public.revisoes_perguntas rp on rp.pergunta_id = p.id
  where m.usuario_id = (select auth.uid())
  group by m.id, m.nome, m.tipo, m.trilha_id, t.nome
  order by t.nome asc nulls last, m.nome asc;
$$;

revoke execute on function public.resumo_materias() from public, anon;
grant execute on function public.resumo_materias() to authenticated;
