-- METADADOS DOS MATERIAIS: título, autores, editora, ano… lidos das primeiras
-- páginas do PDF pela IA (Edge Function `metadados_material`).
--
-- Por que uma tabela, se a listagem vinha só do Storage (0027): o Storage
-- guarda nome/tamanho/data, mas não tem onde pôr "autor" ou "editora", e não dá
-- para pesquisar por eles. A tabela é o índice bibliográfico da estante; o
-- arquivo em si continua no bucket. `caminho` é o elo entre os dois.
--
-- A tabela é OPCIONAL por design: arquivo sem linha aqui (upload antigo, ou PDF
-- ilegível) continua aparecendo na lista, só que sem metadados. Por isso o front
-- casa os dois pelo `caminho` em vez de depender da tabela para listar.

create table public.materiais (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  materia_id bigint not null references public.materias (id) on delete cascade,
  -- caminho completo no bucket: {usuario_id}/{materia_id}/{arquivo}
  caminho text not null,
  nome_arquivo text not null,

  titulo text,
  autores text[],            -- lista: livro com vários autores é a regra, não exceção
  ano integer,
  editora text,
  edicao text,
  isbn text,
  idioma text,
  descricao text,            -- 1-2 frases sobre o conteúdo

  -- de onde vieram os metadados: 'ia' (leu o PDF), 'manual' (usuário corrigiu)
  origem varchar(20) not null default 'ia',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  -- um registro por arquivo; o caminho já é único dentro do bucket
  constraint uq_material_caminho unique (usuario_id, caminho)
);
create index ix_materiais_materia_id on public.materiais (materia_id);

alter table public.materiais enable row level security;

create policy materiais_meta_select on public.materiais
  for select to authenticated
  using (usuario_id = (select auth.uid()));
create policy materiais_meta_insert on public.materiais
  for insert to authenticated
  with check (usuario_id = (select auth.uid()));
create policy materiais_meta_update on public.materiais
  for update to authenticated
  using (usuario_id = (select auth.uid()))
  with check (usuario_id = (select auth.uid()));
create policy materiais_meta_delete on public.materiais
  for delete to authenticated
  using (usuario_id = (select auth.uid()));

-- Hardening da 0012 repetido para a tabela NOVA (o revoke de lá só valeu para
-- as que existiam na época).
revoke all on public.materiais from anon, public;
grant select, insert, update, delete on public.materiais to authenticated;
revoke truncate, trigger, references on public.materiais from authenticated;
